### ISSUE TITLE
最新的可以帮忙打包一个么？为啥我自己打包老不成功。带ldap的

### ISSUE THREAD

**Issue by smile-wang** [linclin/gopub#47]
最新的可以帮忙打包一个么？为啥我自己打包老不成功。带ldap的

**Comment by smile-wang** [comment]
models/user.go:6:2: imported and not used: "github.com/astaxie/beego"
models/user.go:9:2: imported and not used: "library/common"

**Comment by cucued** [comment]
你好，我提交的这个功能，这两天事比较多，有空我改一下并且再测试一下。再提交。

**Comment by cucued** [comment]
改了一下你说的问题，并且在app.conf里加了一些ldap的说明，你试一下。

**Comment by smile-wang** [comment]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-gopub-admin@1.0.0prebuild: vue-gopub-admin@1.0.0
6 info lifecycle vue-gopub-admin@1.0.0build: vue-gopub-admin@1.0.0
7 verbose lifecycle vue-gopub-admin@1.0.0build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-gopub-admin@1.0.0build: PATH: /usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/gopub/vue-gopub/node_modules/.bin:/usr/local/lib/nodejs/node-v12.14.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/opt/gopub/bin:/root/bin
9 verbose lifecycle vue-gopub-admin@1.0.0build: CWD: /opt/gopub/vue-gopub
10 silly lifecycle vue-gopub-admin@1.0.0build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle vue-gopub-admin@1.0.0build: Returned: code: 1 signal: null
12 info lifecycle vue-gopub-admin@1.0.0build: Failed to exec build script
13 verbose stack Error: vue-gopub-admin@1.0.0 build: node build/build.js
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:223:5)
13 verbose stack at ChildProcess. (/usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:223:5)
13 verbose stack at maybeClose (internal/child_process.js:1021:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid vue-gopub-admin@1.0.0
15 verbose cwd /opt/gopub/vue-gopub
16 verbose Linux 3.10.0-1062.9.1.el7.x86_64
17 verbose argv "/usr/local/lib/nodejs/node-v12.14.1-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v12.14.1-linux-x64/bin/npm" "run" "build"
18 verbose node v12.14.1
19 verbose npm v6.13.4
20 error code ELIFECYCLE
21 error

构建前端的时候出现这个问题  可以帮忙看一下么
